### ISSUE TITLE
Error building from sources: multiple definations of main

### ISSUE THREAD

**Issue by denicsdevices** [raspberrypi/pico-tflmicro#11]
Tried to build the project as per the instructions. And about 4% of make progress encountered error regarding multiple definations of man.

**Comment by ZXTube** [comment]
Yeah, I spent the last 2 weeks trying to get this to work, I finally kind of got it to work.
what I did was delete the build folder (if there is one) then run:
1. `mkdir build`
2. `cd build`
3. `cmake .. -G Ninja` -> You could get an error make sure that ninja is in the `PATH` if not, add `C:\location\to\sdk\Pico-C-SDK\ninja` to the path and make sure you're using the right cmake you can write `"C:\location\to\sdk\Pico-C-SDK\cmake\bin\cmake.exe"` instead of `cmake` in step 3
4. `ninja` -> or try running `ninja micro_speech` which will only build the micro_speech example

I found that this worked for me better: https://github.com/iwatake2222/pico-work/tree/master

**Comment by aallan** [comment]
There's just been a fairly large update pulling in three years of upstream changes. Hopefully this should resolve things. If not please reopen an issue.
